import AppKit
import UniformTypeIdentifiers

struct PasteboardSnapshot {
    var changeCount: Int
    var types: [NSPasteboard.PasteboardType]
    var string: String?
    var rtf: Data?
    var rtfd: Data?
    var png: Data?
    var tiff: Data?
    var fileURLs: [URL]
    var html: String?
    var isConcealed: Bool
}

enum PasteboardHelper {
    static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")

    static func snapshot(_ pb: NSPasteboard = .general) -> PasteboardSnapshot {
        let types = pb.types ?? []
        let string = pb.string(forType: .string)
        let rtf = pb.data(forType: .rtf)
        let rtfd = pb.data(forType: .rtfd)
        let png = pb.data(forType: .png)
        let tiff = pb.data(forType: .tiff)
        let html = pb.string(forType: .html)

        var files: [URL] = []
        if let items = pb.pasteboardItems {
            for item in items {
                if let s = item.string(forType: .fileURL), let u = URL(string: s), u.isFileURL {
                    files.append(u)
                }
            }
        }

        let concealed = types.contains(concealedType)
            || types.contains(transientType)
            || types.contains(autoGeneratedType)

        return PasteboardSnapshot(
            changeCount: pb.changeCount,
            types: types,
            string: string,
            rtf: rtf,
            rtfd: rtfd,
            png: png,
            tiff: tiff,
            fileURLs: files,
            html: html,
            isConcealed: concealed
        )
    }

    static func write(_ item: ClipboardItem, to pb: NSPasteboard = .general) {
        pb.clearContents()
        switch item.contentType {
        case .text, .code, .link, .color, .svg, .other:
            if let s = item.textContent { pb.setString(s, forType: .string) }
        case .richText:
            if let d = try? item.content as Data? ?? Data() as Data? {
                _ = d
            }
            pb.setData(item.content, forType: .rtf)
            if let s = item.textContent { pb.setString(s, forType: .string) }
        case .image, .screenshot:
            pb.setData(item.content, forType: .png)
        case .file:
            if let s = item.textContent, let url = URL(string: s) {
                pb.writeObjects([url as NSURL])
            }
        }
    }
}
