import AppKit
import UniformTypeIdentifiers

/// JSON archive of all pasteboard item payloads — used when no single representation parses cleanly.
private struct PasteboardArchive: Codable {
    struct Entry: Codable {
        var type: String
        var data: Data
    }
    var entries: [Entry]
}

struct PasteboardSnapshot {
    var changeCount: Int
    var types: [NSPasteboard.PasteboardType]
    var string: String?
    var rtf: Data?
    var rtfd: Data?
    var png: Data?
    var tiff: Data?
    var fileURLs: [URL]
    var html: String?
    /// Passwords / concealed pasteboard markers (not Universal Clipboard).
    var isConcealed: Bool
    /// Momentary pasteboard content (automation, etc.) — skip unless Universal Clipboard.
    var isTransient: Bool
    /// Synced from another Apple device via Handoff / Universal Clipboard.
    var isUniversalClipboard: Bool
    var universalClipboardDeviceName: String?
    /// Full multi-type archive for lossless restore (see `PasteboardHelper.archiveMIME`).
    var archiveData: Data?
}

enum PasteboardHelper {
    static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    /// Stored in `ClipboardItem.fileMIMEType` when `content` holds a `PasteboardArchive`.
    static let archiveMIME = "application/x-quietclipboard-pasteboard-archive"

    static func snapshot(_ pb: NSPasteboard = .general) -> PasteboardSnapshot {
        let types = pb.types ?? []
        // Guard each read with a type-presence check to avoid unnecessary IPC.
        // Skip tiff if png is present — both represent the same image but png is smaller.
        let string = types.contains(.string) ? pb.string(forType: .string) : nil
        let rtf    = types.contains(.rtf)    ? pb.data(forType: .rtf)      : nil
        let rtfd   = types.contains(.rtfd)   ? pb.data(forType: .rtfd)     : nil
        let png    = types.contains(.png)    ? pb.data(forType: .png)      : nil
        let tiff   = png == nil && types.contains(.tiff) ? pb.data(forType: .tiff) : nil
        let html   = types.contains(.html)   ? pb.string(forType: .html)   : nil

        var files: [URL] = []
        if let items = pb.pasteboardItems {
            for item in items {
                if let s = item.string(forType: .fileURL), let u = URL(string: s), u.isFileURL {
                    files.append(u)
                }
            }
        }

        let isUniversal = types.contains(UniversalClipboardBridge.remoteMarkerType)
        let concealed = types.contains(concealedType)
        let transient = types.contains(transientType)
        let autoGenerated = types.contains(autoGeneratedType)
        let origin = isUniversal ? UniversalClipboardBridge.origin(from: pb) : nil

        return PasteboardSnapshot(
            changeCount: pb.changeCount,
            types: types,
            string: string,
            rtf: rtf,
            rtfd: rtfd,
            png: png,
            tiff: tiff,
            fileURLs: files,
            html: html,
            isConcealed: concealed && !isUniversal,
            isTransient: (transient || autoGenerated) && !isUniversal,
            isUniversalClipboard: isUniversal,
            universalClipboardDeviceName: origin?.displayName,
            archiveData: archiveData(from: pb)
        )
    }

    /// Captures every data payload on the pasteboard for lossless restore.
    static func archiveData(from pb: NSPasteboard = .general) -> Data? {
        var entries: [PasteboardArchive.Entry] = []
        let skip: Set<String> = [
            concealedType.rawValue,
            transientType.rawValue,
            autoGeneratedType.rawValue
        ]
        for pasteItem in pb.pasteboardItems ?? [] {
            for type in pasteItem.types {
                guard !skip.contains(type.rawValue), let data = pasteItem.data(forType: type), !data.isEmpty else {
                    continue
                }
                entries.append(PasteboardArchive.Entry(type: type.rawValue, data: data))
            }
        }
        guard !entries.isEmpty else { return nil }
        return try? JSONEncoder().encode(PasteboardArchive(entries: entries))
    }

    static func restoreArchive(_ data: Data, to pb: NSPasteboard = .general) -> Bool {
        guard let archive = try? JSONDecoder().decode(PasteboardArchive.self, from: data),
              !archive.entries.isEmpty else { return false }
        pb.clearContents()
        let item = NSPasteboardItem()
        for entry in archive.entries {
            item.setData(entry.data, forType: NSPasteboard.PasteboardType(entry.type))
        }
        return pb.writeObjects([item])
    }

    static func write(_ item: ClipboardItem, to pb: NSPasteboard = .general) {
        if item.fileMIMEType == archiveMIME, restoreArchive(item.content, to: pb) {
            return
        }

        pb.clearContents()
        switch item.contentType {
        case .text, .markdown, .code, .link, .color, .svg:
            if writeRichRepresentations(item, to: pb) { return }
            if let s = meaningfulPlainText(item) {
                pb.setString(s, forType: .string)
            }
        case .other:
            if writeRichRepresentations(item, to: pb) { return }
            if let s = meaningfulPlainText(item) {
                pb.setString(s, forType: .string)
            } else if !item.content.isEmpty {
                pb.setData(item.content, forType: .string)
            }
        case .richText:
            if writeRichRepresentations(item, to: pb) { return }
            if let s = meaningfulPlainText(item) {
                pb.setString(s, forType: .string)
            }
        case .image, .screenshot:
            pb.setData(item.content, forType: .png)
        case .file:
            if let s = item.textContent, let url = URL(string: s) {
                pb.writeObjects([url as NSURL])
            }
        }
    }

    /// Writes RTF / HTML / RTFD from stored content. Returns true if anything was written.
    private static func writeRichRepresentations(_ item: ClipboardItem, to pb: NSPasteboard) -> Bool {
        guard !item.content.isEmpty else { return false }
        switch item.fileMIMEType {
        case "text/html":
            if let html = String(data: item.content, encoding: .utf8) {
                pb.setString(html, forType: .html)
                if let s = meaningfulPlainText(item) { pb.setString(s, forType: .string) }
                return true
            }
        case "application/rtfd":
            pb.setData(item.content, forType: .rtfd)
            if let s = meaningfulPlainText(item) { pb.setString(s, forType: .string) }
            return true
        case "text/rtf":
            pb.setData(item.content, forType: .rtf)
            if let s = meaningfulPlainText(item) { pb.setString(s, forType: .string) }
            return true
        default:
            break
        }
        // Misclassified clips: try RTF/HTML parsing from raw bytes.
        if (try? NSAttributedString(
            data: item.content,
            options: [.documentType: NSAttributedString.DocumentType.rtf],
            documentAttributes: nil
        )) != nil {
            pb.setData(item.content, forType: .rtf)
            if let s = meaningfulPlainText(item) { pb.setString(s, forType: .string) }
            return true
        }
        if let html = String(data: item.content, encoding: .utf8),
           html.range(of: "<[a-zA-Z]", options: .regularExpression) != nil {
            pb.setString(html, forType: .html)
            if let s = meaningfulPlainText(item) { pb.setString(s, forType: .string) }
            return true
        }
        return false
    }

    private static func meaningfulPlainText(_ item: ClipboardItem) -> String? {
        guard let s = item.textContent?
            .trimmingCharacters(in: .whitespacesAndNewlines), !s.isEmpty else { return nil }
        return s
    }
}
